version: '3'

services:
  test-db:
    restart: always
    container_name: test-db
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-test
    ports:
      - "3306:3306"

  # phpmyadmin
  test-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - test-db
    links:
      - test-db:db